version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: poesam-laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: poesam-db
    environment:
      MYSQL_DATABASE: poesam
      MYSQL_ROOT_PASSWORD: rootpass
    ports: 
      - "3306:3306"
 